site_name: Math Notes
theme:
  name: material
  palette:
    primary: black
  #logo: img/favicon.png
  features:
    - navigation.expand
  hljs_languages:
    - glsl

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition
  
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
